### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by xunoaib**
Fixes a few typos and grammar

### CODE REVIEW

**Review by TechStudent10 — APPROVED** [review]

**Comment by swoops** [comment]
Thank you @xunoaib! Sorry I missed it. Thanks @TechStudent11 for causing a ping that I did catch.

All looks good for this.

There is a small bug but that is something I have to live with I think. Changing the config schema (ie fixing "patern") means the old config wont work anymore. So anyone upgrading EV will have EV silently fail when the new spelling does not find anything in storage. I will address this in another pull though, unless you want to try and tackle it.

**Comment by TechStudent10** [comment]
> Thank you @xunoaib! Sorry I missed it. Thanks @TechStudent11 for causing a ping that I did catch.

No problem :). I didn't know that approving causes a ping.

Also, don't just thank me, thank @PwnFunction for starring this repo. If he didn't do that, I wouldn't have approved this PR.

**Comment by swoops** [comment]
> No problem :). I didn't know that approving causes a ping.

I didn't know you could review the code :)
I appreciate the help.

**Comment by TechStudent10** [comment]
Once again, no prob.

Edit: @PwnFunction thanks for the reaction. Appreciate it.

**Pull request merged**
